language: de

pipeline:
- name: SpacyNLP
  model: de_core_news_md
- name: SpacyTokenizer
- name: SpacyEntityExtractor
  dimensions: 
  - PERSON
- name: SpacyFeaturizer
- name: LexicalSyntacticFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
- name: EntitySynonymMapper
- name: DucklingEntityExtractor
  url: "http://duckling:8000"
  dimensions: 
  - time
  locale: de_DE
  timezone: Europe/Berlin
- name: EntitySynonymMapper
- name: DIETClassifier
  constrain_similarities: true
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
- name: RegexFeaturizer

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 100
  max_history: 5
  constrain_similarities: true
#  featurizer: 
#  - name: MaxHistoryTrackerFeaturizer
#    max_history: 5
#    state_featurizer:
#    - name: LabelTokenizerSingleStateFeaturizer
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "utter_default"
  enable_fallback_prediction: True
