# This is a basic workflow to help you get started with Actions

name: Rasa-training-testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  [push]

jobs:
  setup:
    name: Setup
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip<20"
          pip install -r requirements.txt

  training:
    name: Train model
    run: rasa train

  test-model:
    name: Test Model
    runs-on: ubuntu-latest
    needs: [training]

    steps:
      - name: Test stories
        run: rasa test core

      - name: Upload model
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models/



