# This is a basic workflow to help you get started with Actions

name: Rasa-training-testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  [push]

jobs:
  training:
    name: Train Model
    runs-on: ubuntu-latest

    env:
      RUN_TRAINING: false

    steps:
      - name: Download and link spacy packages
        run: |
          pip install spacy
          python -m spacy download en_core_web_md
          python -m spacy link en_core_web_md en
      - uses: actions/checkout@v1
      - name: Rasa Train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_test: false
          data_validate: true
          github_token: ${{ secrets.TOKEN }}

  test-model:
    name: Test Model
    runs-on: ubuntu-latest
    needs: [training]

    steps:
      - uses: actions/checkout@v1
      - name: Rasa Test
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_train: false
          test_type: all
          data_validate: true
          cross_validation: true
          publish_summary: true
          github_token: ${{ secrets.TOKEN }}
      - name: Upload model
        uses: actions/upload-artifact@main
        with:
          name: model
          path: models/



