name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'

jobs:
  build-model:
    name: Build, test, and upload model
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip"
        pip install -r requirements.txt
        python -m spacy download de_core_news_md
    - name: Train model
      run: |
        rasa train
    - name: Run Tests
      run: |
        rasa test core --stories tests/conversation_tests.yml
    - name: Upload Model to RasaX
      run: |
        model_name=`ls models/* | head -n 1`
        curl -k -F "model=@"$model_name"" "http://blender.zkm.de/api/projects/default/models?api_token=9c069c93ca3b9e760a8eea08f437ad8d5b077743"
      # curl -X PUT "http://blender.zkm.de/api/projects/default/models/"$model_name"/tags/production"
