# This is a basic workflow to help you get started with Actions

name: Rasa-training-testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  [push]

jobs:
  build-model:
    name: Build, test, and upload model
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<20"
        pip install -r requirements.txt
    - name: Train model
      run: |
        rasa train
    - name: Run Through Test Stories
      run: |
        rasa test core --stories test_stories/stories.yaml --fail-on-prediction-errors



